### ISSUE TITLE
Installation documentation - need some more detail

### ISSUE THREAD

**Issue by WheresWes** [mzakharo/tubby#1]
I stumbled across this git by chance.  I already have a couple of gravity sensors working in my pool but this looks to be a much more elegant solution so I purchased the feather v2 and accessories.  However I'm struggling to get it work as I dont think I am approaching the installation correctly.

"copy wifi_example.yaml to wifi.yaml and edit the new file
Connect the board via USB and enter esphome run tubby.yaml"

Could you elaborate on how you perform these steps?  I'm used to flashing the esp with esphome and then pasting the yaml into it.. However there seem to be a number of dependancies here which means it fails to compile.  Could you add a bit more detail for idiots like me?  Id really love to get this working!

**Comment by mzakharo** [comment]
Can you please post the error logs you are seeing? Also what version of esphome you are using.  esphome should be able to pull the dependencies automatically when you run `esphome run tubby.yaml` .

**Comment by WheresWes** [comment]
Ok so my problem stemmed from the fact that I was not aware of the ESPhome CLI which is installed on a PC.  I have set that up and I can now compile and flash the FeatherS2 without any issue.  However after that - nothing.  It wont connect to the wifi I set up in the wifi.yaml.  Tried to add a fallback AP to the yaml but that also does not appear.  Tried to get logging by serial on the same com port as it was flashed on but it wont connect so no idea how to determine what the issue is.  Could it be related to the deep sleep?

**Comment by WheresWes** [comment]
On a side note.. what is the reason for removing the ambient light sensor?  I have not done this yet

**Comment by WheresWes** [comment]
OK.. ET phoned home.. caught it as it was powered on and now successfully added to home assistant!  Now I can complete the rest of the wiring etc.  IF you could please advise regarding the ambient light sensor?

My thanks for this project!

**Comment by mzakharo** [comment]
Yeah. I should probably add in the instructions that you have to wait 15
minutes before logs appear and device attempts to connect to HA. You can
probably keep the amb sensor to keep track of the sun. I had it removed to
save power in earlier versions of the project before I added solar.

**Comment by WheresWes** [comment]
Thankyou.
You seem pretty clued up with micro controllers.  I have a small job I could use some help with.  I would pay for your time.  Just let me know how I can get in touch.
